/* Additional record code for FmiTest_Model generated by the OpenModelica Compiler OpenModelica 1.16.0~dev-479-g8630a30. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "FmiTest_Model_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

